// <auto-generated />
using EmployeeDAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeDAL.Migrations
{
    [DbContext(typeof(EmpContext))]
    partial class EmpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeDAL.Models.EmpProfile", b =>
                {
                    b.Property<int>("EmpCode")
                        .HasColumnType("int")
                        .HasColumnName("EmpCode");

                    b.Property<int>("DeptCode")
                        .HasColumnType("int")
                        .HasColumnName("DeptCode");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EmpName");

                    b.HasKey("EmpCode");

                    b.ToTable("EmpProfile");

                    b.HasData(
                        new
                        {
                            EmpCode = 100,
                            DeptCode = 1,
                            Email = "scott@gmail.com",
                            EmpName = "Scott"
                        },
                        new
                        {
                            EmpCode = 101,
                            DeptCode = 2,
                            Email = "tiger@gmail.com",
                            EmpName = "Tiger"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
