// <auto-generated />
using DeptDAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DepartmentDAL.Migrations
{
    [DbContext(typeof(DeptContext))]
    partial class DeptContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DepartmentDAL.Models.Department", b =>
                {
                    b.Property<int>("DeptCode")
                        .HasColumnType("int")
                        .HasColumnName("DeptCode");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DeptName");

                    b.HasKey("DeptCode");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            DeptCode = 1,
                            DeptName = "Hr"
                        },
                        new
                        {
                            DeptCode = 2,
                            DeptName = "Accounts"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
